on:
  pull_request:
    branches: [main]

name: Check package

jobs:
  setup-r:
    runs-on: ubuntu-latest
    name: Setup R and check/document/lint package
    steps:
      - uses: actions/checkout@v6

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: release
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        id: setup-deps
        with:
          cache: always
          extra-packages: |
            any::lintr
            any::cyclocomp
            any::rcmdcheck
            any::devtools
            any::covr
            local::.

      - name: Lint
        id: lint
        if: ${{ !cancelled() && steps.setup-deps.outcome != 'failure' }}
        run: lintr::lint_package()
        shell: Rscript {0}
        env:
          LINTR_ERROR_ON_LINT: true

      - uses: r-lib/actions/check-r-package@v2
        if: ${{ !cancelled() && steps.setup-deps.outcome != 'failure' }}
        id: check
        with:
          upload-snapshots: true
          error-on: '"error"'
        env:
          _R_CHECK_EXCESSIVE_IMPORTS_: 0

      - name: Run devtools::document()
        if: ${{ !cancelled() && steps.setup-deps.outcome != 'failure' }}
        id: document
        run: |
          # ensure repo in clean state (after check step)
          git clean -fd
          # ensure we have updated NAMESPACE/man etc
          Rscript -e "devtools::document()"
          # show the git status
          echo "::group:: git status"
          git status --porcelain
          echo "::endgroup::"
          # if the repo isn't in a clean state, error
          if [ -n "$(git status --porcelain)" ]; then
            echo "::error::\`devtools::document()\` has not been run"
            exit 1
          fi
        shell: bash

      - name: Report errors
        if: failure()
        run: |
          echo "Errors in the workflow"
          exit 1

  air-format:
    runs-on: ubuntu-latest
    name: Check formatting of code with air

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v6

      - name: Install Air
        uses: posit-dev/setup-air@v1

      - name: Check Formatting
        run: air format . --check
