on:
  push:
    branches:
      - 129-jarl-gha
  pull_request:
    branches:
      - 129-jarl-gha
  workflow_dispatch:

name: jarl Check

permissions: read-all

jobs:
  jarl-check:
    name: jarl check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: etiennebacher/setup-jarl@v0.1.1
